---
- name: get public ip
  shell: dig +short myip.opendns.com @resolver1.opendns.com 2>/dev/null || curl -s --retry 2 icanhazip.com
  register: ip_address
  when: node_ip is not defined

- name: setting ip to use
  set_fact:
    node_ip: "{{ip_address.stdout}}"
  when: node_ip is not defined

- name: Install Orion Node
  import_tasks: "install.yaml"
  when: install | default(False) | bool

- name: Update Writer Node
  import_tasks: "update.yaml"
  when: update | default(False) | bool