---
- name: Verifiying health check daemon is installed
  shell: ls /lib/systemd/system/ | grep health-check.service
  register: healthCheck
  ignore_errors: yes

- name: Stopping Health Check Daemon before updating
  import_tasks: "stop-health-check.yaml"
  when: (healthCheck.stdout == 'health-check.service')

- name: stop enclave
  import_tasks: "stop-orion.yaml"

- name: Update Orion Node
  import_tasks: "update-orion.yaml"

- name: Copy service file to systemd
  copy:
    src: "{{ role_path }}/files/orion.service"
    dest: /lib/systemd/system/orion.service
    mode: 0775

- name: Enable service orion
  service:
    name: orion
    enabled: yes

- name: Verifying certificate is created
  shell: ls /root/lacchain/orion/certificates | grep orion_cer.pem
  register: certificate
  ignore_errors: yes

- name: Create Orion Certificate
  import_tasks: "init-orion-certificate.yaml"
  when: (certificate.stdout != 'orion_cer.pem')

- name: Verifiying nginx is installed
  shell: ls /lib/systemd/system/ | grep nginx.service
  register: nginx
  ignore_errors: yes

- name: install nginx
  import_tasks: "prepare-nginx.yml"
  when: (nginx.stdout != 'nginx.service')

- name: Restarting Health Check Daemon
  import_tasks: "start-health-check.yaml"
  when: (healthCheck.stdout == 'health-check.service')

- name: start orion
  import_tasks: "start-orion.yaml"
