---
- name: initializing constellation
  debug:
    msg: initializing constellation

- name: create orion directories
  file:
    path: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - { dest: "~/lacchain/orion", mode: "0440" }
    - { dest: "~/lacchain/orion/keystore", mode: "0440" }

- name: copy password to file
  copy:
    dest: ~/lacchain/tmp/.account_pass
    content: |
      {{password}}

- name: create certificates
  import_tasks: "init-orion-certificate.yaml"

- name: generate configuration orion file
  template:
    src: "orion.j2"
    dest: "~/lacchain/orion/orion.conf"
    force: yes

- name: generate pair keys
  shell: cat ~/lacchain/tmp/.account_pass | orion --generatekeys nodeKey
  args:
    chdir: ~/lacchain/orion/keystore

- name: Generate shell script to execute orion service
  template:
    src: "startorion.j2"
    dest: "~/lacchain/start-orion.sh"
    mode: 0775
    force: yes

- name: Copy service file to systemd
  copy:
    src: "{{ role_path }}/files/orion.service"
    dest: /lib/systemd/system/orion.service
    mode: 0775

- name: Enable service orion
  service:
    name: orion
    enabled: yes
