---
- name: install dependencies for  {{ ansible_distribution }}
  import_tasks: "ubuntu-dependencies.yml"
  when: ansible_distribution |lower == 'ubuntu'

- name: install dependencies for  {{ ansible_distribution }}
  import_tasks: "rhel-dependencies.yml"
  when: (ansible_distribution |lower == 'redhat') or (ansible_distribution |lower == 'centos')

- name: install java for {{ ansible_distribution }}
  import_tasks: "install-java-ubuntu.yaml"
  when: ansible_distribution |lower == 'ubuntu'

- name: install java for {{ ansible_distribution }}
  import_tasks: "install-java-centos.yaml"
  when: (ansible_distribution |lower == 'redhat') or (ansible_distribution |lower == 'centos')  

- name: install docker for {{ ansible_distribution }}
  import_tasks: "install-docker-ubuntu.yaml"
  when: ansible_distribution |lower == 'ubuntu'

- name: install docker for {{ ansible_distribution }}
  import_tasks: "install-docker-redhat.yaml"
  when: (ansible_distribution |lower == 'redhat') or (ansible_distribution |lower == 'centos')

- name: install Besu
  import_tasks: "install-besu.yaml"

- name: init besu
  import_tasks: "init-besu.yaml"

- name: install nginx
  import_tasks: "prepare-nginx.yml"

- name: init tunning
  import_tasks: "init-tuning.yaml"

- name: start node
  import_tasks: "start-node.yaml"

- name: start ethstats client
  import_tasks: "start-ethstats-client.yaml"
  when: (networkT == '0') or (networkT == '1')


