---
- name: Acceptance Verification
  import_tasks: "agreements-acceptance.yml"
  
- name: install dependencies for  {{ ansible_distribution }}
  import_tasks: "ubuntu-dependencies.yml"
  when: ansible_distribution |lower == 'ubuntu'

- name: install dependencies for  {{ ansible_distribution }}
  import_tasks: "rhel-dependencies.yml"
  when: (ansible_distribution |lower == 'redhat') or (ansible_distribution |lower == 'centos')

- name: install java for {{ ansible_distribution }}
  import_tasks: "install-java-ubuntu.yaml"
  when: ansible_distribution |lower == 'ubuntu'

- name: install java for {{ ansible_distribution }}
  import_tasks: "install-java-centos.yaml"
  when: (ansible_distribution |lower == 'redhat') or (ansible_distribution |lower == 'centos')  

- name: install docker for {{ ansible_distribution }}
  import_tasks: "install-docker-ubuntu.yaml"
  when: ansible_distribution |lower == 'ubuntu'

- name: install docker for {{ ansible_distribution }}
  import_tasks: "install-docker-redhat.yaml"
  when: (ansible_distribution |lower == 'redhat') or (ansible_distribution |lower == 'centos')

- name: install pantheon
  import_tasks: "install-pantheon.yaml"

- name: init pantheon
  import_tasks: "init-pantheon.yaml"

- name: install orion
  import_tasks: "install-orion.yaml"

#- name: init orion
#  import_tasks: "init-orion.yaml"

- name: start node
  import_tasks: "start-node.yaml"
  when: first_node

#- name: start ethstats client
#  import_tasks: "start-ethstats-client.yaml"

#- name: Prepare Health Check Service
#  import_tasks: "prepare-health-check.yaml"

- name: install nginx
  import_tasks: "prepare-nginx.yml"

- name: clean files
  import_tasks: "clean-files.yaml"

- name: init tunning
  import_tasks: "init-tuning.yaml"