- name: Delete previous nginx.conf
  file:
       path: /etc/nginx/nginx.conf
       state: absent

- name: Copy ngix.conf file
  copy:
    src: "{{ role_path }}/files/nginx.conf"
    dest: /etc/nginx/nginx.conf
    mode: 0644

- name: get public ip
  shell: dig +short myip.opendns.com @resolver1.opendns.com 2>/dev/null || curl -s --retry 2 icanhazip.com
  register: node_ip

- name: Copy ssl config file
  template:
    src: "ssl.conf.j2"
    dest: "/etc/nginx/conf.d/ssl.conf"
    mode: 0644

- name: Configure nginx.service(always restart)
  shell: cp /lib/systemd/system/nginx.service tempservice && cat tempservice | sed -E 's/vice]/vice]\nRestart=always/' > /lib/systemd/system/nginx.service && rm tempservice
  become: true