---
- name: Update besu
  debug:
        msg: "Updating Besu"

- name: Download specified Besu source code
  git:
        repo: "https://github.com/hyperledger/besu"
        dest: "/tmp/besu"
        version: "{{ besu_release_commit }}"

- name: Building Besu
  shell: "gradle build -x test"
  args:
        chdir: /tmp/besu/

- name: Standarizing name
  shell:  mv *.tar.gz besu.tar.gz
  args:
        chdir: /tmp/besu/build/distributions

- name: Preparing temporal folder
  shell: rm -rf /tmp/transit/ && mkdir /tmp/transit #deleting and creating a new
  args:
    warn: false

- name: Extract the Besu tarball  
  unarchive:
        src: "/tmp/besu/build/distributions/besu.tar.gz"
        dest: /tmp/transit #/usr/local
        copy: no

- name: Renaming extracted file
  shell: mv * besu
  args:
        chdir: /tmp/transit

- name: stop enclave #stopping node before starting the update process
  import_tasks: "stop-orion.yaml"        

- name: stop besu #stopping node before starting the update process
  import_tasks: "stop-node.yaml"        

- name: Deleting old folders
  shell: rm -rf /usr/local/besu
  args:
    warn: false

- name: moving files to /usr
  shell: mv /tmp/transit/besu /usr/local
        
 #removing old link
- name: Deleting old installed versions of besu or pantheon
  file:
       path: /usr/bin/{{ item.dest }}
       state: absent
  with_items:
        - { dest: "pantheon" }
        - { dest: "pantheon.bat" }
        - { dest: "besu"}
        - { dest: "besu.bat"}

- name: Support for deployments prior to centos support
  file:
       path: /usr/local/bin/{{ item.dest }}
       state: absent
  with_items:
        - { dest: "pantheon" }
        - { dest: "pantheon.bat" }
        - { dest: "besu"}
        - { dest: "besu.bat"}          

- name: Symbolic link for besu (pantheon and besu are linked to BESU)
  file:
        src: "/usr/local/besu/bin/{{ item.src }}"
        dest: "/usr/bin/{{ item.dest }}"
        state: link
  with_items:
        - { src: "besu", dest: "pantheon" }
        - { src: "besu.bat", dest: "pantheon.bat" }
        - { src: "besu", dest: "besu" }
        - { src: "besu.bat", dest: "besu.bat" }

- name: start orion
  import_tasks: "start-orion.yaml"        

- name: start node
  import_tasks: "start-node.yaml"

- name: clearing unnecessary folders
  shell: rm -rf /tmp/transit
  args:
    warn: false  