---
- name: stop enclave #stopping node before starting the update process
  import_tasks: "stop-orion.yaml"

- name: stop pantheon #stopping node before starting the update process
  import_tasks: "stop-node.yaml" 

- name: Update orion
  debug:
      msg: "Updating Orion"

- name: Download specified orion source code
  git:
        repo: "https://github.com/PegaSysEng/orion"
        dest: "/tmp/orion"
        version: "{{ orion_release_commit }}"

- name: Building Orion
  shell: "./gradlew build -x test"
  args:
        chdir: /tmp/orion/

- name: Standarizing name
  shell:  mv *.tar.gz orion.tar.gz
  args:
        chdir: /tmp/orion/build/distributions

- name: Preparing temporal folder
  shell: rm -rf /tmp/transit/ && mkdir /tmp/transit #deleting and creating a new
  args:
    warn: false

- name: Extract the orion tarball  
  unarchive:
        src: "/tmp/orion/build/distributions/orion.tar.gz"
        dest: /tmp/transit
        copy: no

- name: Renaming extracted file
  shell: mv * orion
  args:
        chdir: /tmp/transit

- name: Deleting old folders
  shell: rm -rf /usr/local/orion
  args:
    warn: false

- name: moving files to /usr
  shell: mv /tmp/transit/orion /usr/local

- name: clearing unnecessary folders
  shell: rm -rf /tmp/transit
  args:
    warn: false

- name: Deleting old installed versions of orion
  file:
       path: /usr/local/bin/{{ item.dest }}
       state: absent
  with_items:
        - { dest: "orion" }
        - { dest: "orion.bat" }

- name: Symbolic link for orion
  file:
        src: "/usr/local/orion/bin/{{ item.src }}"
        dest: "/usr/local/bin/{{ item.dest }}"
        state: link
  with_items:
        - { src: "orion", dest: "orion" }
        - { src: "orion.bat", dest: "orion.bat" }

- name: start orion
  import_tasks: "start-orion.yaml"

- name: start besu
  import_tasks: "start-node.yaml"