---
- name: Update orion
  debug:
      msg: "Updating Orion"

- name: previous clearing
  shell: rm -rf /tmp/orion && mkdir /tmp/orion
  args:
    warn: false      

- name: pull orion binaries
  get_url:
    url: "https://bintray.com/consensys/binaries/download_file?file_path=orion-{{ orion_release_version}}.tar.gz"
    dest: "/tmp/orion/orion.tar.gz"

- name: Preparing temporal folder
  shell: rm -rf /tmp/transit/ && mkdir /tmp/transit #deleting and creating a new
  args:
    warn: false

- name: Extract the Orion tarball  
  unarchive:
        src: "/tmp/orion/orion.tar.gz"
        dest: /tmp/transit #/usr/local
        copy: no

- name: Renaming extracted file
  shell: mv * orion
  args:
    chdir: /tmp/transit        

- name: Deleting old folders
  shell: rm -rf /usr/local/orion
  args:
    warn: false

- name: moving files to /usr
  shell: mv /tmp/transit/orion /usr/local

- name: Deleting old installed versions of orion
  file:
       path: /usr/bin/{{ item.dest }}
       state: absent
  with_items:
        - { dest: "orion" }
        - { dest: "orion.bat" }

- name: Support for deployments prior to centos support
  file:
       path: /usr/local/bin/{{ item.dest }}
       state: absent
  with_items:
        - { dest: "orion" }
        - { dest: "orion.bat" }        

- name: Symbolic link for orion
  file:
        src: "/usr/local/orion/bin/{{ item.src }}"
        dest: "/usr/bin/{{ item.dest }}"
        state: link
  with_items:
        - { src: "orion", dest: "orion" }
        - { src: "orion.bat", dest: "orion.bat" }

- name: clearing unnecessary folders
  shell: rm -rf /tmp/transit && rm -rf /tmp/orion
  args:
    warn: false