---
- name: Install orion
  debug:
      msg: "Installing Orion"

- name: Include installation libsodium for  {{ ansible_distribution }}
  import_tasks: "ubuntu-install-libsodium.yaml"
  when: ansible_distribution |lower == 'ubuntu'

#- name: Fix Libsodium for {{ ansible_distribution }}
#  import_tasks: "rhel-install-libsodium.yaml"
#  when: (ansible_distribution |lower == 'redhat') or (ansible_distribution |lower == 'centos')

- name: Include installation leveldb for  {{ ansible_distribution }}
  import_tasks: "ubuntu-install-leveldb.yaml"
  when: ansible_distribution |lower == 'ubuntu'

#- name: Download orion source code
#  git:
#      repo: "https://github.com/PegaSysEng/orion.git"
#      dest: "/tmp/orion"
#      version: 65749f00ada641c4dfd5982b293a4e59962be695

#- name: Building Orion
#  shell: "gradle build -x test"
#  args:
#      chdir: /tmp/orion/
- name: Download Orion Binaries
  get_url:
      url: "https://bintray.com/consensys/binaries/download_file?file_path=orion-1.3.2.tar.gz"
      dest: "/tmp"

- name: Extract the Orion tarball
  unarchive:
      src: "/tmp/orion-1.3.2.tar.gz"
      dest: /usr/local
      copy: no

- name: Symbolic link for pantheon
  file:
      src: "/usr/local/orion-1.3.2/bin/{{ item.src }}"
      dest: "/usr/bin/{{ item.dest }}"
      state: link
  with_items:
      - { src: "orion", dest: "orion" }
      - { src: "orion.bat", dest: "orion.bat" }
