---
# tasks file for docker-ce-ansible-role

- name: Remove previous docker installation
  yum:
    name: "{{ docker_cleanup_packages_EL }}"
    state: absent

- name: Install prerequisite packages
  yum:
    name: "{{ docker_prerequisite_packages_EL }}"
    state: present

- name: Enable additional repository (for RHEL only)
  rhsm_repository:
    name: "rhel-7-server-extras-rpms"
    state: present
  when: ansible_distribution == "RedHat"

- name: Install additional prerequisite packages (for RHEL only)
  yum:
    name: "{{ docker_prerequisite_packages_EL_RHEL }}"
    state: present
  when: ansible_distribution == "RedHat"

- name: Import Docker CE repository gpg key
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: Add Docker CE repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    force: yes
    owner: root
    group: root
    mode: 0644

- name: Install Docker CE
  yum:
    name: docker-ce
    state: present
    update_cache: yes

- name: Enable docker
  shell: systemctl enable docker.service
  become: yes

- name: Start docker
  shell: systemctl start docker.service
  become: yes
