---
- name: set mainnet as network chosen
  set_fact:
    network: "mainnet"
  when: (networkT == '0')

- name: set protestet as network chosen
  set_fact:
    network: "protestnet"
  when: (networkT == '1') 

- name: set devnet as network chosen
  set_fact:
    network: "devnet"
  when: (networkT == '2')   

- name: Deploying node
  debug:
    msg: You are deploying a BOOT on {{network}}

- name: Install Bootnode
  import_tasks: "install.yaml"
  when: install | default(False) | bool

- name: Update Bootnode
  import_tasks: "update.yaml"
  when: update | default(False) | bool
